export const SET_USER = 'SET_USER';
export const REMOVE_USER = 'REMOVE_USER';
export const ATEMPT_LOGIN = 'ATEMPT_LOGIN';
export const LOGING_IN_USER = 'LOGING_IN_USER';
export const CHECK_EMAIL_EXIST = 'CHECK_EMAIL_EXIST';

export const USER = {
  CHECK_EMAIL_EXISTS_REQUEST: 'CHECK_EMAIL_EXISTS_REQUEST',
  CHECK_EMAIL_EXISTS_SUCCESS: 'CHECK_EMAIL_EXISTS_SUCCESS',
  CHECK_EMAIL_EXISTS_FAIL: 'CHECK_EMAIL_EXISTS_FAIL',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  SET: 'SET'
};
