export const USER = {
  CHECK_EMAIL_EXISTS_REQUEST: 'CHECK_EMAIL_EXISTS_REQUEST',
  CHECK_EMAIL_EXISTS_SUCCESS: 'CHECK_EMAIL_EXISTS_SUCCESS',
  CHECK_EMAIL_EXISTS_FAIL: 'CHECK_EMAIL_EXISTS_FAIL',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  SET: 'SET',

  SIGNUP_REQUEST: 'SIGNUP_REQUEST',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  SIGNUP_FAIL: 'SIGNUP_FAIL',

  AUTH_MODAL_OPEN: 'AUTH_MODAL_OPEN'
};

export const POST = {
  CREATE_REQUEST: 'CREATE_REQUEST',
  CREATE_SUCCESS: 'CREATE_SUCCESS',
  CREATE_FAIL: 'CREATE_FAIL',

  SET: 'SET'
};
