export const USER = {
  CHECK_EMAIL_EXISTS_REQUEST: 'CHECK_EMAIL_EXISTS_REQUEST',
  CHECK_EMAIL_EXISTS_SUCCESS: 'CHECK_EMAIL_EXISTS_SUCCESS',
  CHECK_EMAIL_EXISTS_FAIL: 'CHECK_EMAIL_EXISTS_FAIL',

  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAIL: 'LOGIN_FAIL',

  SET: 'SET'
};
